version: '3.8'

services:
  wildfly:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wildfly-dev
    ports:
      - "8080:8080"   # Porta applicazione
      - "9990:9990"   # Porta console amministrazione
    networks:
      - wildfly-network
    restart: unless-stopped

networks:
  wildfly-network:
    driver: bridge
