MS_PERSONA_GIURIDICA_ENDPOINT: https://api-intranet.sviluppo.inps.it/rest/servizi-t/ms00045
#MS_PERSONA_GIURIDICA_ENDPOINT: http://localhost:8080
#DATAPOWER_CLIENTID: #{DATAPOWER_CLIENT_ID}#
#DATAPOWER_CLIENTSECRET: #{DATAPOWER_CLIENT_SECRET}#
DATAPOWER_CLIENTID: b43e6ff22cc16e2be221b6206d92872d
DATAPOWER_CLIENTSECRET: c0194278209b668f8e62e9c757f494ab

IAP_CODAPP: WW

PASSIUTIL_IPASSIUTIL: PassiUtilFake
PASSIUTIL_IDSERVIZIO: 718

#da utilizzare con PassiUtilFake
PASSIUTIL_TIPOUTENTEINTERNETFAKE: 1
PASSIUTIL_CFCITTADINOFAKE: VLIDNC43H03F839T
PASSIUTIL_NOMECITTADINOFAKE: DOMENICO
PASSIUTIL_COGNOMECITTADINOFAKE: IEVOLI
PASSIUTIL_SESSOCITTADINOFAKE: M
PASSIUTIL_EMAILCITTADINOFAKE: TEST@EMAIL.COM
PASSIUTIL_TIPOPINCITTADINOFAKE: 2SPI

BUSSOLA_URL: http://bussola.svil.inps/getheadersirio.aspx
BUSSOLA_ID_APPLICAZIONE: 920

ENABLE_CORS: true
ALLOWED_ORIGIN: *
#ALLOW-FROM: 
CSRF_COOKIE_NAME: XSRF-TOKEN
CSRF_HEADER_NAME: X-XSRF-TOKEN

#DATA POWER
DATAPOWER_APPNAME: WA03631
DATAPOWER_APPKEY: WA03631
DATAPOWER_USERID: 1
DATAPOWER_IDENTITYPROVIDER: 1


#WSPROTOCOLLO
WSPROTOCOLLO_ENDPOINT: https://ws.svil.inps/Ws.Net/WSProtocollo
WSPROTOCOLLO_TITOLARIO: 19.3.1
WSPROTOCOLLO_OGGETTO: RICHIESTA ISCRIZIONE AZIENDA PUBBLICA

#CREATEPDF
WSCREATEPDF_ENDPOINT: https://ws.svil.inps/Adobe/CreatePdf

#DOCUMENTALE
WSDSATTACHMENTDOCUMENTSERVICE_ENDPOINT: https://ws.svil.inps/Ws.Net/wsDSAttachmentDocumentService

#WSNAGRAFICATRIBUTARIA
WSANAGRAFICATRIBUTARIA_ENDPOINT: https://ws.svil.inps/AT511_service/services/DatiAnagraficiCompleti
WSANAGRAFICATRIBUTARIA_ENTE: INPS_GDP_WA03631
WSANAGRAFICATRIBUTARIA_SEDE: INTERNET

#WSSEDI
WSSEDIINPS_ENDPOINT: https://ws.svil.inps/Ws.Net/wsSediINPS

#WSFAQNEWSAVVISI
WSFAQNEWS_ENDPOINT: https://ws.svil.inps/Ws.Net/WSFaqNewsAvvisi
WSFAQNEWS_IDAPPLICAZIONE: 77
WSFAQNEWS_TIPO: N

#WSGESTOREFEDBACK
WSGESTOREFEEDBACK_ENDPOINT: https://ws.svil.inps/Ws.Net/WSGestoreFeedback
WSGESTOREFEEDBACK_APPLICAZIONE: WA03631_IscrizioneAziendaPubblicaWeb

#WS_DELEGHE
WSGESTIONEDELEGHEAUSERVICE_ENDPOINT:https://ws.svil.inps/Ws.Net/WSGestioneDelegheAU

#WSICONA - INVIO EMAIL
WSICONA_ENDPOINT: https://ws.svil.inps/Ws.Net/WSIcona

WSANAGRAFICAUNICACONTRIBUTIVA_ENDPOINT : https://ws.svil.inps/Ws.Net/WSLeggiAnagrUnicaContr
#CLOG
CLOG_PARAMETRI_CODAPP: WA03631_IscrizioneAziendaPubblicaWeb
CLOG_IDEVENTO_IAPW_CONSULTARICHIESTE: 3805001
CLOG_IDEVENTO_IAPW_CONSULTADETTAGLIO: 3805002
CLOG_IDEVENTO_IAPW_INSERIMENTORICHIESTA: 3805003
CLOG_IDEVENTO_IAPW_ELIMINARICHIESTA: 3805004
CLOG_IDEVENTO_IAPW_CONSULTADOCUMENTI: 3805005
CLOG_IDEVENTO_IAPW_CONSULTADETTAGLIO_VARIAZIONE: 3805006
CLOG_IDEVENTO_IAPW_INSERIMENTORICHIESTA_VARIAZIONE: 3805007
CLOG_IDEVENTO_IAPW_CONSULTADOCUMENTI_VARIAZIONE: 3805008
